name: HTML Checker
on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  build:
    name: HTML Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: anishathalye/proof-html@v2
        with:
          directory: ./
          check_css: false
          check_favicon: false
          ignore_url: |
            https://www.linkedin.com/in/ferran-buireu
