name: Link Checker
permissions:
  contents: read
  issues: write
on:
  workflow_dispatch:
  pull_request:
  push: 
jobs:
  build:
    name: Link Checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2.4.1
      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./reports/link-checker-output.md
          labels: report, automated issue
